indexcards/config/routes.rb
Indexcards::Application.routes.draw do
  resources :cards

end

indexcards/app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :back, :front, :title
end

indexcards/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])
    if params['show_answer'] == "true"
      @answer =  @card.back
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end
end

indexcards/app/helpers/cards_helper.rb
module CardsHelper
end

indexcards/app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :front %><br />
    <%= f.text_field :front %>
  </div>
  <div class="field">
    <%= f.label :back %><br />
    <%= f.text_field :back %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

indexcards/app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

indexcards/app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Front</th>
    <th>Back</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cards.each do |card| %>
  <tr>
    <td><%= card.title %></td>
    <td><%= card.front %></td>
    <td><%= card.back %></td>
    <td><%= link_to 'Show', card %></td>
    <td><%= link_to 'Edit', edit_card_path(card) %></td>
    <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Card', new_card_path %>

indexcards/app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

indexcards/app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>
<h1>An Indexcard!</h1>
<p>
  <b>Title:</b>
  <%= @card.title %>
</p>
<hr>
<hr>
<p>
  <b>Front:</b>
  <%= @card.front %>
</p>

<% if @answer %>
<p>
  <b>Answer:</b>
  <%= @answer %>
</p>
<p>
<%= link_to 'Hide Answer', card_path(@card,show_answer: false)  %>	
</p>
<% else %>
<p>
<%= link_to 'Show Answer', card_path(@card,show_answer: true)  %>	
</p>

<% end %>


<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

indexcards/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Indexcards</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>